version: "3.9"

services:
  postgres:
    image: postgres:16
#    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookhouse
    ports:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d bookhouse" ]
      interval: 2s
      timeout: 2s
      retries: 30

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

  server:
    container_name: server-bookhouse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/bookhouse
      TEST_DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/bookhouse_test

volumes:
  pgdata:
